### PR TITLE
Implement setuid/setuid32

### PR DESCRIPTION
**Pull request by Ronsor**
This implements the `setuid` and `setuid32` system calls and adds permission checks to `setresgid`.

### CODE REVIEW

**Comment by tbodt** [comment]
`setuid` is specified as changing the uid, euid, and suid. Also it should be allowed to set your euid to your uid or suid, even if neither are 0.

**Comment by Ronsor** [comment]
setuid now has proper semantics

**Comment by tbodt** [comment]
It should also allow setting your euid to your uid or suid, even if you're not root.

**Comment by Ronsor** [comment]
currently `setreuid` are unimplemented; the proper behavior with setting the euid works fine in `setresuid`

**Comment by tbodt** [comment]
A better implementation of setreuid would be to call setresuid with -1 as the last parameter. In fact, all the set*uid functions should probably just call setresuid.

**Comment by tbodt** [comment]
setuid still isn't quite right, it doesn't allow a non-root process to set its uid to its euid. The check on setresuid is pretty broken, the correct behavior is specified here: http://man7.org/linux/man-pages/man2/setresuid.2.html#DESCRIPTION

**Comment by tbodt** [comment]
setuid is now implemented, closing.

**Pull request closed without merging**
