### PR TITLE
In The Process of adding More theming options

### PR DESCRIPTION
**Pull request by Regularcheckm8**
Started the production of creating custom themes with copy/pasting support for RGB values and saving them to themes.Ive even added a few more themes just cause i didn't finish this in one day
Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-19 at 10 36 20_iphonexspacegrey_portrait

It shows up as an entirely different category but in the end of the Day there wont be a preset themes, there will be a "My Themes" section. I might be able to have themes upload-able to iCloud But for now this is all I got. 

Simulator Screen Shot - iPhone 11 Pro Max - 2019-10-19 at 17 06 24_iphonexspacegrey_portrait

Day One Of Work
First Pull Request

### CODE REVIEW

**Comment by tbodt** [comment]
I would prefer you use the git command line to make pull requests, so the PR doesn't end up as hundreds of "Add files via upload" commits.

**Comment by Regularcheckm8** [comment]
If anyone wants to critique please do (im gonna need it)

**Comment by Regularcheckm8** [comment]
also sorry lol

**Comment by tbodt** [comment]
This PR has all the changed files added to the root of the repo instead of where they go, I'd really recommend the git command line to make it hard to make that mistake. I can point you at some resources for learning git if you like.

**Comment by Regularcheckm8** [comment]
geez thanks. i really haven't made PRs before so i would love to be directed in a good direction

**Comment by Regularcheckm8** [comment]
Imma close this

**Comment by Regularcheckm8** [comment]
Taking up valuable space 😂

**Comment by Rexogamer** [comment]
the heck

**Comment by Regularcheckm8** [comment]
Ha what’s wrong

**Comment by Mnpn03** [comment]
Why close this?

**Comment by Regularcheckm8** [comment]
Ummm 🤔 
Cause I’m my perspective I totally flopped on this one and I think I have a different version of the design I want to try out. TBH there’s no real good reason to close this but if Theo wants to reopen this he can

**Comment by Regularcheckm8** [comment]
Also if my new idea works we won’t have that stupid theming array/dictionary taking up space

**Pull request closed without merging**
