### PR TITLE
Download the latest alpine minirootfs

### PR DESCRIPTION
**Pull request by hrubymar10**
Don't hardcode latest alpine version, but download the latest one automatically instead.

### CODE REVIEW

**Comment by filfat** [comment]
👏

**Comment by tbodt** [comment]
This isn't a good idea because it gives the build a non-immutable dependency. Sometimes an Alpine upgrade breaks things, so I don't want it to happen implicitly. Similar to why people lock dependency versions with package-lock.json.

**Comment by ntindle** [comment]
Should there be a way to run this explicitly without having to go through the terminal?

**Comment by tbodt** [comment]
What do you mean?

**Comment by ntindle** [comment]
More of a far in the future update to latest. I thought about it and it doesn’t really have a place right now to me

**Pull request closed without merging**
