### PR TITLE
implement fcntl F_SETFL

### PR DESCRIPTION
**Pull request by lunixbochs**

### CODE REVIEW

**Comment by tbodt** [comment]
The problem with this is the values of O_NONBLOCK and O_APPEND are different on Linux and Darwin. F_GETFL also has this problem.

**Comment by lunixbochs** [comment]
Do you have a generalized structure for converting enums yet?

**Comment by tbodt** [comment]
My handling of this issue in open() is here: https://github.com/tbodt/ish/blob/master/fs/real.c#L41

**Comment by lunixbochs** [comment]
Are you open to having one big C file that's a bunch of functions like enum_in_mmap() enum_out_mmap() enum_in_open(), etc, with the same sort of pattern?

**Comment by tbodt** [comment]
I would prefer to have functions like that closer to where they're used. For example, functions to map socket flags are defined in sock.h.

**Comment by tbodt** [comment]
Merged along with flag mapping and a few other fixes.

**Pull request merged**
