### PR TITLE
Travis conf to build for iOS

### PR DESCRIPTION
**Pull request by xffzero**
its shiny
it works (maybe)

### CODE REVIEW

**Comment by tbodt** [comment]
Can we get it to build both mac and linux?

**Comment by xffzero** [comment]
i think we can build some stuff on linux, not the actual xcodeproj though

**Comment by tbodt** [comment]
No, the app won't build on linux, but I'd like to keep doing linux builds like we are currently.

**Comment by xffzero** [comment]
sounds good, i'll try and get it to work

**Comment by tbodt** [comment]
Closing in favor of #98

**Pull request closed without merging**
