### PR TITLE
Upgrade Alpine to 3.9.0

### PR DESCRIPTION
**Pull request by 0b101**
https://alpinelinux.org/posts/Alpine-3.9.0-released.html

### CODE REVIEW

**Comment by tbodt** [comment]
Have you tested to make sure things are generally not broken? There were previously some issues with alpine edge where a lot of things like gcc would fail with "illegal instruction".

**Comment by 0b101** [comment]
During testing I did not see any issues with gcc. When installing nano (on the simulator) there were a couple errors related to ncurses unable to create and modify directories, but nano appears to function normally.

**Comment by tbodt** [comment]
OK then, it's probably safe. The errors from installing nano are from the macOS filesystem being case insensitive. By a miraculous coincidence the iOS filesystem is case sensitive so everything works fine there.

**Comment by saagarjha** [comment]
Recent versions of the simulator should simulate a case-sensitive filesystem, just FYI.

**Comment by tbodt** [comment]
Interesting, when did they add that?

**Comment by saagarjha** [comment]
[Mavericks][
https://worthdoingbadly.com/casesensitive-iossim/], it looks like.

**Pull request merged**
