### PR TITLE
Add e2e and move tests to tests/ directory

### PR DESCRIPTION
**Pull request by MatthewMerrill**
Tests are defined by a subdirectory of `tests/e2e/` containing a `test.sh` and `expected.txt`. After tests are run the output can be analyzed in `e2e_out/`.

### Example of failed test (changed a number in the test file):
```
### Running Test: fpu              ###
!!! Failed: fpu
1,5d0
< 16.12
< -15.88
< 1.92
< 0.01
< 133.33
6a2,6
> -15.87
> 2.08
> 0.01
> 123.08
> 16.14
### Running Test: hello            ###
### Passed: 1/2 (50.00%)           ###
```

### Example of all passes:
```
### Running Test: fpu              ###
### Running Test: hello            ###
### Passed: 2/2 (100.00%)          ###
```

Exit code is 1 if any test failed, so this can be integrated into travis testing.

### CODE REVIEW

**Comment by MatthewMerrill** [comment]
added meson stuffs

**Comment by tbodt** [comment]
Just one last thing, can you put the e2e.bash script in the tests/e2e directory?

**Comment by MatthewMerrill** [comment]
Done

**Comment by tbodt** [comment]
The travis build is still failing. Could you disable the tests on interpreter mode? After that I'm ready to merge.

**Comment by MatthewMerrill** [comment]
Passing now :fortnite_default_dance:

**Pull request merged**
