### PR TITLE
Add wiki to Readme.md

### PR DESCRIPTION
**Pull request by ntindle**

### CODE REVIEW

**Comment by tbodt** [comment]
Seems like a good idea but I don't like the formatting.

**Comment by ntindle** [comment]
How would you like it to look?

**Comment by Rexogamer** [comment]
He made [a commit](https://github.com/tbodt/ish/commit/5d312b4b4906211d1c7c66584f3a4bba7fb6a45b)  that added the wiki to the README, presumably in the way he wanted it to look.

**Comment by ntindle** [comment]
Oh, thanks for letting me know, I didn’t notice

________________________________

**Pull request closed without merging**
